### ISSUE TITLE
Three-letter BIP39 word always returns ambiguous lookup result?

### ISSUE THREAD

**Issue by dapperdachshunds** [radixdlt/babylon-wallet-ios#820]
A user on Telegram is facing an issue where the iOS wallet keeps telling him some words are invalid. These words happen to be three-letter words. He claims to have confirmed that the words are correct and on the BIP39 word list.

I did some digging, and while I'm not very familiar with Swift and can't actually test this myself, I may have some pointers to where this issue (if it exists) might come from. It looks to me like any three-letter word will always return an ambiguous lookup result, which in turn results in a failed validation state.

- When the word field loses focus (e.g. you go to the next one), it triggers a lookup of your input here: https://github.com/radixdlt/babylon-wallet-ios/blob/7b925413a24c850e0a029d74ab5ebd1c0bffb731/Sources/Features/ImportMnemonic/ImportMnemonic.swift#L291-L292
- If the result of that lookup is that the word is known, but ambiguous (as in, there are more results that start with those letters), which is the case for at least some three-letter words, it sets hasFailedValidation to true: https://github.com/radixdlt/babylon-wallet-ios/blob/7b925413a24c850e0a029d74ab5ebd1c0bffb731/Sources/Features/ImportMnemonic/ImportMnemonic.swift#L293-L295
- My guess is that the 'ambiguous' result is returned here, because there are simply more words starting with those three letters: https://github.com/radixdlt/babylon-wallet-ios/blob/7b925413a24c850e0a029d74ab5ebd1c0bffb731/Sources/Cryptography/Mnemonic/BIP39/BIP39%2BWordList.swift#L147-L149
... as a result of this simple 'starts with' filter here: https://github.com/radixdlt/babylon-wallet-ios/blob/7b925413a24c850e0a029d74ab5ebd1c0bffb731/Sources/Cryptography/Mnemonic/BIP39/BIP39%2BWordList.swift#L131

For the English BIP39 list, lookups start becoming unambiguous from 4 characters or more if I'm not mistaken, so from that point it shouldn't be an issue.

Possible solution: check for an exact match first, which should cover exactly the case for a three-letter word (since >=4 letters is unambiguous and <3 letters doesn't match any words so that's always invalid)

**Comment by stultulon** [comment]
I managed to reproduce this and now I feel mentally ill. Here’s what I found:

If another word on the BIP39 wordlist shares the first 3 letters of a 3-letter word (e.g. pen/penalty), the wallet accepts the 3-letter word only if you enter it right the first time. If you accidentally enter a different word, then immediately go back and correct it to “pen” it’ll say it’s an invalid word.

There’s actually a way to correct it to “pen” after the fact, but you have to follow very specific steps. Let’s say word 15 should be pen, but you enter “penalty.” You’d have to:

1) Erase “penalty” and leave word 15 blank.
2) Skip ahead and enter word 16, or any other word.
3) Go back to word 15 and enter “pen”
4) The wallet accepts it as a valid word.

The most important step is 1, because it’ll still say “pen” is invalid if you don’t clear word 15 before entering the next word (i.e. if you leave word 15 as “penalty” then enter word 16, then go back and erase penalty and enter pen, the wallet will still think “pen” is invalid).

I’m sure this will be corrected with all due haste. There are more bizarre subtleties that I skipped, but the bug probably stems from the fact that no two BIP39 words have the same first four letters and we’re only dealing with three letters.

**Comment by CyonAlexRDX** [comment]
Thank you for thorough analysis! We will take a look at this soon!

**Comment by CyonAlexRDX** [comment]
I'm working on this in #870, here is a good test mnemonic (valid):
`"add addict address pen penalty pencil act action actor actress zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo tip"`

And a Profile which uses it
[add_addict__zoo_tip.json](https://github.com/radixdlt/babylon-wallet-ios/files/13177512/add_addict__zoo_tip.json)

@umair-rdx we can use this Profile and mnemonic to test we have fixed this issue. I'm gonna write some unit tests as well

**Comment by CyonAlexRDX** [comment]
<img width="510" alt="Screenshot 2023-10-26 at 14 56 36" src="https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/79ba38ef-3302-4311-92df-3d77f6609c36">

for testing here is a QR code of an Olympia wallet with 2 accounts using 12 word mnemonic: 
"add addict address pen penalty pencil act action actor actress zoo wreck"

**Comment by CyonAlexRDX** [comment]
[add_addict__zoo_tip_with_Olympia_accounts.json](https://github.com/radixdlt/babylon-wallet-ios/files/13177749/add_addict__zoo_tip_with_Olympia_accounts.json)

And here is a Profile where 24 word babylon device factor source (mnemonic) is:
`"add addict address pen penalty pencil act action actor actress zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo tip"`

but with the two Olympia accounts (same as QR code above), controlled by mnemonic:
`"add addict address pen penalty pencil act action actor actress zoo wreck"`

**Comment by CyonAlexRDX** [comment]
@stultulon @dapperdachshunds thanks for reporting, this has been fixed in https://github.com/radixdlt/babylon-wallet-ios/pull/870 and will be part of upcoming release 1.1.0
