### ISSUE TITLE
Ledger Nano <> Brave connectivity issues on old macOS

### ISSUE THREAD

**Issue by chiragverma** [radixdlt/babylon-wallet-ios#885]
Radix wallet does not detect ledger nano s with radix ios wallet. Used the new babylon app and did all the updates it doesn't detect ledger nano s when the app is open but it can detect when the app is closed

**Comment by dapperdachshunds** [comment]
Just to make sure: have you clicked past the "Pending Ledger review" screen?

**Comment by CyonAlexRDX** [comment]
@chiragverma  thanks for getting in touch. We are working on publishing our contributing guidelines, but while we do, we would like to clarify that Github Issues are primarily meant for the purpose of reporting problems or concerns _relating to the source **code**_, rather than functioning as an open bug tracker. This means that reported issues on Github may be closed and reported in our internal tracking system or added to our roadmap.

In order for us to be able to help you, please make sure to provide as much detail as possible, including:
* iPhone model
* iOS version
* Browser
* Browser version
* iOS Wallet App version
* Connector Extension version
* Radix Ledger App version

Ledger Nano
* Firmware version
* microcontroller version
* bootloader version
* Radix Babylon Ledger App Version

And just to ensure... you are indeed launching the Radix BABYLON Ledger app, and not the Radix Olympia Ledger app? :)

**Comment by CyonAlexRDX** [comment]
@chiragverma thanka but I do actually need explicit versions, "latest" does not give me the information I need to help you, since many software companies do progressive rollout/delivery, thus it is possible you have a later version than what I can see/or the reverse. Which is why I need explicit version numbers.

It is also a way for me to see directly that "aha, this user is using Olympia Ledger App, since he/she said 0.3.1 but we never released such a version with Babylon Ledger app which had 0.7.7 as lowest".

It would also be helpful to know your host OS, is it Windows, Linux or macOS? And which version? 

How did you install the Connector Extension (CE)? Through extension store in Chrome or direct download from our GitHub? (Also need to know CE version as stated above)

And just to make sure, when you let Chrome (CE) try to connect to your ledger - is Ledger Live or any other browser running? Only one single application can claim connection with Ledger, why you must ensure only Chrome is doing so. In fact, now for the purpose of debugging- best if you shut down all other application beside one single Chrome window, to mimimise risk of any other app claiming connectivity.

Did you ever get to see the small black/greyish window popped out by Chrome asking you to allow it connect to your Ledger? It is a "list" (with only one item) showing "Ledger Nano S" (or similar)? Or did you never get to that step?

**Comment by CyonAlexRDX** [comment]
@chiragverma please respond with All asked info, you missed some, eg browser version and Ledger firmware versions.

You are using quite an old macOS, do you have the ability to update it?

**Comment by CyonAlexRDX** [comment]
@chiragverma hey you didn't tell us the firmware of the Ledger Nano device itself. It is three versions:
MCU
Secure Elements
Boot loader
(You told me version of Ledger Live app, not the ledger device which is what we need to know)

**Comment by CyonAlexRDX** [comment]
@chiragverma also can you please try Chrome instead of Brave, we officially support Chrome at the moment. 

So try that, and tell me Ledger firmware.

If does not work:

Probably best if you reach out to hello@radixdlt.com

So that my colleagues who work with community support can communicate with you.

And I suspect this is not an iOS wallet issue but it is more a connectivity issue between your old macOS host, browser and ledger device.

**Comment by siy** [comment]
Is it correct understanding that LedgerLive constantly proposes you to update Babylon Ledger App?

**Comment by siy** [comment]
> the app was a big failure this is the first time i am having this connectivity issues

I'm really sorry that you're experiencing problems. Unfortunately, not everything depends on us and our code. There are many moving parts involved and some of them are out of our control. We're doing our best to nail down and resolve the issue.

**Comment by siy** [comment]
May I ask you to do the following? : 
- connect device, enter pin and start app (go past "Pending preview")
- wait about a minute 
- try to connect to it from wallet

**Comment by GhenadieVP** [comment]
For any further assistance, if needed, please contact us at hello@radixdlt.com.
